server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:chaveamentoRobos}?sslmode=${PGSSLMODE:disable}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:aluno}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=${JWT_SECRET:8435b0af1f151997e98a5bd8ff75a56e7b1461acd449398b782eff0b1d10be5}

app.cors.origem-frontend=${FRONTEND_URL:http://localhost:5173}


supabase.url=${SUPABASE_URL:https://oypjbnyzptfguhdgvdci.supabase.co}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cGpibnl6cHRmZ3VoZGd2ZGNpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTA4MTY0OCwiZXhwIjoyMTA0NjU3NjQ4fQ.YmM4AtRLjOCWBwZJa81YlANL1ySKa4NOQ9W-rfBpWPI}
supabase.bucket=${SUPABASE_BUCKET:times}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect